// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABVBiD1fHwGtcl9taEUN_2qRfcG70QNXY',
    appId: '1:1078699292112:web:6295f6d12b0a94a0ebf5d5',
    messagingSenderId: '1078699292112',
    projectId: 'chat-app-b9dfc',
    authDomain: 'chat-app-b9dfc.firebaseapp.com',
    storageBucket: 'chat-app-b9dfc.firebasestorage.app',
    measurementId: 'G-F6FCRS2EEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHi64sqOZF8ykALKlrzeQR71bKaxAt8M4',
    appId: '1:1078699292112:android:5647158fd88c6859ebf5d5',
    messagingSenderId: '1078699292112',
    projectId: 'chat-app-b9dfc',
    storageBucket: 'chat-app-b9dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbMK4InSuyPZkXmnwa5tAJE6Yp5WDRNU',
    appId: '1:1078699292112:ios:37db72051d1cfb3debf5d5',
    messagingSenderId: '1078699292112',
    projectId: 'chat-app-b9dfc',
    storageBucket: 'chat-app-b9dfc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbMK4InSuyPZkXmnwa5tAJE6Yp5WDRNU',
    appId: '1:1078699292112:ios:37db72051d1cfb3debf5d5',
    messagingSenderId: '1078699292112',
    projectId: 'chat-app-b9dfc',
    storageBucket: 'chat-app-b9dfc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABVBiD1fHwGtcl9taEUN_2qRfcG70QNXY',
    appId: '1:1078699292112:web:6725d6611628da03ebf5d5',
    messagingSenderId: '1078699292112',
    projectId: 'chat-app-b9dfc',
    authDomain: 'chat-app-b9dfc.firebaseapp.com',
    storageBucket: 'chat-app-b9dfc.firebasestorage.app',
    measurementId: 'G-F3XH4G6223',
  );
}
